rabbit-shocker/rabbit

- lib/rabbit/keys.rb
We need a lot of patches to run rabbit command.
> Drop old Gtk+2 support

- rabbit.gemspec
We can use gtk3 following command:
$ bundle install --path vendor/bundle
$ RABBIT_GTK_VERSION=3 bundle exec ruby bin/rabbit slide.rab
> Add development devendency

- lib/rabbit/frame.rb
- lib/rabbit/progress.rb
- lib/rabbit/search-window.rb
- lib/rabbit/video-window.rb
Suppress following message:
lib/rabbit/progress.rb:7:in `initialize': 'Gtk::Window::POPUP' has been deprecated. Use 'Gtk::Window::Type::POPUP' or ':popup'.
> Use symbol for window type

- lib/rabbit/renderer/display/magnifier.rb
- lib/rabbit/renderer/display/spotlight.rb
Because gdk3 defines Gdk::EventType::BUTTON* not Gdk::Event::BUTTON*.
> Use Gdk::EventType::BUTTON* instead of Gdk::Event::BUTTON*

- lib/rabbit/gtk.rb
- lib/rabbit/info-window.rb
- lib/rabbit/renderer/display/clutter-embed.rb
- lib/rabbit/renderer/display/drawing-area-base.rb
- lib/rabbit/renderer/display/drawing-area-primitive.rb
Because gtk3 use Gdk::EventMask::*_MASK
> Use Gdk::EventMask::*_MASK instead of Gdk::Event::*_MASK

- lib/rabbit/gtk.rb
- lib/rabbit/renderer/display/base.rb
This is the first step to replace Gdk::Window#size with Gdk::Window#{width,height}.
We may use Gdk::Window#size in other places.
> Use Gdk::Window#{width,height} instead of Gdk::Window#size with index for gtk3

- lib/rabbit/renderer/display/drawing-area-base.rb
Because gtk3 does not have Gdk::GC.
> Use Cairo API to blackout/whiteout

- lib/rabbit/parser/ext/entity.rb
Thank you for great presentation tool.
I get this warnings when I run `rabbit` command.
```
/Users/naiad/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rabbit-2.1.8/lib/rabbit/parser/ext/entity.rb:355: warning: duplicated key at line 2409 ignored: "Dagger"
/Users/naiad/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rabbit-2.1.8/lib/rabbit/parser/ext/entity.rb:357: warning: duplicated key at line 2411 ignored: "dagger"
```
> Remove duplicate Dagger and dagger keys

- lib/rabbit/command/rabbit.rb
This will clear the error below that is raised when running `rabbit` with an option like `--page-margin=72,36`
```
[FATAL]
undefined method `parse_four_dimensions' for Rabbit::Utils:Module
```
> Use Utils.parse_four_way instead of Utils.parse_four_dimensions

- lib/rabbit/command/rabbit.rb
Rabbit has supported Markdown format since v1.0.5, 
but choose dialog hasn't supported Markdown file filter. I've fixed it.
> Add Markdown file filter to choose dialog

- lib/rabbit/parser/markdown/converter.rb
When Rabbit read markdown file which includes horizontal rules, Rabbit was crashed by NoMethodError.
This is a test case.
```markdown
subtitle
:   Presentation with Markdown
author
:   Foo Bar
institution
:   COZMIXNG
theme
:   rabbit
A presentation tool
* A
---
* B
* C
```
This patch is workaround.
Rabbit will ignore horizontal rules, because Rabbit doesn't support it.
> Ignore horizontal rule

- lib/rabbit/renderer/display/magnifier.rb
- lib/rabbit/renderer/display/spotlight.rb
If Rabbit's window aspect ratio is not same as slide's one, there are two problems.
1. spotlight's background mask will not cover slide fullly
2. magnifier will not be displayed on cursor's position
This change should resolve those issues.
> fix margin handlings

- lib/rabbit/info-window.rb
- lib/rabbit/source/memory.rb
オリジナルのソースから情報ウィンドウへのソースにコピーする際、extension の情報が落ちるため、情報ウィンドウでのソースのパースが失敗します。
extension をコピーすることでこの問題を修正します。
> ファイル指定で markdown ファイルを開いたとき、情報ウィンドウのスライド表示が正しくない問題の修正

- doc/en/index.rd
- doc/ja/index.rd
Because "prototype.js" is removed by 29330103.
> Remove reference to "prototype.js" in doc

- lib/rabbit/command/rabbit-slide.rb
- po/en/rabbit.po
- po/fr/rabbit.po
- po/ja/rabbit.po
config yaml file that generated from `rabbit-slide new` has `licenses` field  but not support `--licenses` option in `rabbit-slide new`.
> Add support '--licenses' option in 'rabbit-slide new'

- lib/rabbit/theme/image-slide-number/image-slide-number.rb
I have set `@margin_left = 300` because my slide backgroung has black area on the left side (see below).
However, modifying `@margin_left` causes an issue that Usa Taro won't reach the goal (see below).
My patch will fix this issue and work well even if you modify both `@margin_left` and `@margin_right`
> fix an issue that Usa Taro will not reach the goal if you modify @margin_left

- lib/rabbit/parser/ext/image.rb
Suppress a error message.
```
rabbit/lib/rabbit/parser/ext/image.rb:112: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
> Use URI.open

- doc/en/install/homebrew.rd
- doc/ja/install/homebrew.rd
Homebrewを使用したインストール方法が色々と古くなっていたので現状に即した記述に更新しました。なお、パッケージにおいてはこれをインストールしていればとりあえず動いた、というのを確かめられただけで、これが最小構成かどうかの検証はできていません。
> Update install guide using Homebrew on macos

- doc/en/install/homebrew.rd
- doc/ja/install/homebrew.rd
macOSのHomebrewを使ったインストールのマニュアルについて、以下の２点をフォローしています。
* `brew install gtk+3` としないとGTK 3が入らなくてrabbitが動かないので、そのように変更しました。
* 環境によってHomebrewでインストールしたライブラリのPathが異なるので、環境に応じた`DYLD_LIBRARY_PATH`の設定ができるように記載を変更しました。
> Update to installation guide for macOS with Homebrew

- doc/en/usage/rabbit.rd
- doc/ja/usage/rabbit.rd
Since https://github.com/rabbit-shocker/rabbit/commit/77bc67542bb42256aae28f5ffb07ea2825183cf2
> Fix document that default public level is all

- doc/en/how-to-make/markdown.md
- doc/en/how-to-make/rd.rd
- doc/ja/how-to-make/markdown.md
- doc/ja/how-to-make/rd.rd
I add documentation about title slide meta tags.
> Add documentation about title slide meta tags

- rabbit.gemspec
Because drb is no longer a default gem from Ruby 3.4.
https://github.com/ruby/ruby/pull/9629
> Add drb to rabbit.gemspec
